### ISSUE TITLE
結果画面「～キャラです」が合わない時がある

### ISSUE THREAD

**Issue by kumiko-koshino** [moemake/moe_make#5]
最後にくるであろうゲスエロがプレイなので変な感じ。(尿道キャラです)
ゲスエロとエロのところ必要に応じて「〇〇プレイ」などにします。

![2015-01-24 21 16 06](https://cloud.githubusercontent.com/assets/10472134/5887359/56350946-a40e-11e4-966f-481fdde966b6.png)

**Comment by hazumu** [comment]
修正done
